language: go

sudo: false

go:
    - tip

install:
  - go get -u -tags experimental ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - sh test.sh
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
    email: false
